#!/usr/bin/env node
const clefairy = require("clefairy");
const readStdin = require("./lib/read-stdin");

clefairy.run({}, async (options, ...args) => {
  if (!process.stdin.isTTY) {
    input = await readStdin();
  } else {
    input = args;
  }

  const output = {};

  const items = JSON.parse(input);

  while (items.length > 0) {
    output[items.shift()] = items.shift();
  }

  console.log(JSON.stringify(output, null, 2));
});
