#!/usr/bin/env node
const clefairy = require("clefairy");
const readStdin = require("./lib/read-stdin");

clefairy.run({}, async (options, ...args) => {
  let input;
  if (!process.stdin.isTTY) {
    input = readStdin();
  } else {
    input = args;
  }

  console.log(JSON.parse(input).join("\t"));
});
